spring.application.name=java-ai-langchain4j
server.port=8080
logging.level.root=info

spring.profiles.active=local

# 厂商 1：deepSeek
# API Key 从环境配置文件中获取
langchain4j.open-ai.chat-model.base-url=${AI_CHAT_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
langchain4j.open-ai.chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.open-ai.chat-model.model-name=${AI_CHAT_MODEL_NAME:deepseek-v3}

langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

# 厂商 2：Qwen
# Ollama 服务地址从环境配置文件中获取
langchain4j.ollama.chat-model.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
langchain4j.ollama.chat-model.model-name=${OLLAMA_MODEL_NAME:qwen3:0.6b}
langchain4j.ollama.chat-model.temperature=${OLLAMA_TEMPERATURE:0.8}
langchain4j.ollama.chat-model.timeout=${OLLAMA_TIMEOUT:PT60S}

langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true

# 厂商 3：阿里百炼平台
# API Key 从环境配置文件中获取
langchain4j.community.dashscope.chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=${DASHSCOPE_CHAT_MODEL_NAME:qwen-max}

langchain4j.community.dashscope.embedding-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.embedding-model.model-name=${DASHSCOPE_EMBEDDING_MODEL_NAME:text-embedding-v3}

langchain4j.community.dashscope.streaming-chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=${DASHSCOPE_STREAMING_MODEL_NAME:qwen-plus}

# mysql mongodb redis配置已转移至dev/local配置中
