spring.application.name=java-ai-langchain4j
server.port=8080
logging.level.root=info

spring.profiles.active=local

# 厂商 1：deepSeek
# API Key 从环境配置文件中获取
langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.open-ai.chat-model.model-name=deepseek-v3

langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

# 厂商 2：Qwen
# Ollama 服务地址从环境配置文件中获取
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=deepseek-r1:14b
langchain4j.ollama.chat-model.temperature=0.8
langchain4j.ollama.chat-model.timeout=PT60S

langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true

# 厂商 3：阿里百炼平台
# API Key 从环境配置文件中获取
langchain4j.community.dashscope.chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.chat-model.model-name=qwen-max

langchain4j.community.dashscope.embedding-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.embedding-model.model-name=text-embedding-v3


# 流式输出的模型
langchain4j.community.dashscope.streaming-chat-model.api-key=${DASH_SCOPE_API_KEY}
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus

# 多模态模型配置
#langchain4j.open-ai.chat-model.vision-base-url=${DASHSCOPE_VISION_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
#langchain4j.open-ai.chat-model.vision-api-key=${DASH_SCOPE_API_KEY}
#langchain4j.open-ai.chat-model.vision-model-name=qwen-vl-max

# mysql mongodb redis配置已转移至dev/local配置中

# Pinecone 向量数据库配置
pinecone.api.key=${PINECONE_API_KEY}
pinecone.index=interview-assistant-index
pinecone.cloud=AWS
pinecone.region=us-east-1

# 面试题库配置
interview.questions.path=src/main/resources/content
# 面试简历配置
resume.storage.path=E:/NanJiStar_Database/05-java-ai-interview-workspace/src/main/resources/resumes
# 题库上传知识库开关
interview.questions.auto-load=false

# 使用 Pinecone
vector.store.type=pinecone

# 使用 ChromaDB
#vector.store.type=chroma
#chroma.baseUrl=http://localhost:8000

# 阿里云OSS 上传图片 配置与定义分离，便于后期修改 维护
aliyun.oss.endpoint: https://oss-cn-beijing.aliyuncs.com
aliyun.oss.bucketName: java-ai-shytest
aliyun.oss.region: cn-beijing


